//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AISS_WHT
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public int LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_ObjectType { get; set; }
        public Nullable<int> U_BaseEntry { get; set; }
        public Nullable<int> U_BaseSeries { get; set; }
        public string U_BaseNum { get; set; }
        public Nullable<System.DateTime> U_DueDate { get; set; }
        public Nullable<System.DateTime> U_PostingDate { get; set; }
        public Nullable<System.DateTime> U_TaxDate { get; set; }
        public string U_Branch { get; set; }
        public string U_BpCode { get; set; }
        public string U_BpName { get; set; }
        public string U_BpAddr { get; set; }
        public string U_BpTaxID { get; set; }
        public string U_BpBrnCode { get; set; }
        public string U_WHTType { get; set; }
        public string U_WHTSeries { get; set; }
        public string U_WHTNum { get; set; }
        public Nullable<short> U_SeqNum { get; set; }
        public Nullable<short> U_Condition { get; set; }
        public string U_CondOther { get; set; }
        public Nullable<decimal> U_TotalWHTAmt { get; set; }
        public Nullable<int> U_TransId { get; set; }
        public string U_Printed { get; set; }
        public Nullable<System.DateTime> U_SubmitDate { get; set; }
        public Nullable<int> U_SubmitId { get; set; }
        public string U_InvNum { get; set; }
        public string U_AcctCode { get; set; }
        public string U_FormatCode { get; set; }
        public Nullable<decimal> U_WHTBaseAmt { get; set; }
        public Nullable<int> U_BaseLine { get; set; }
    }
}
