//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AISS_ALLOCATION
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public int LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string U_ISS_AllocateCode { get; set; }
        public string U_ISS_AllocateName { get; set; }
        public string U_ISS_FormatCode { get; set; }
        public string U_ISS_AccountCode { get; set; }
        public string U_ISS_AccountName { get; set; }
        public Nullable<decimal> U_ISS_Allocate1 { get; set; }
        public Nullable<decimal> U_ISS_Allocate2 { get; set; }
        public Nullable<decimal> U_ISS_Allocate3 { get; set; }
        public Nullable<decimal> U_ISS_AllocateTotal { get; set; }
        public string U_ISS_FormatCodeFrom { get; set; }
        public string U_ISS_AccountCodeFrom { get; set; }
        public string U_ISS_FormatCodeTo { get; set; }
        public string U_ISS_AccountCodeTo { get; set; }
        public string U_ISS_CreFormatCode { get; set; }
        public string U_ISS_CreAccountCode { get; set; }
        public string U_ISS_CreAccountName { get; set; }
        public Nullable<decimal> U_ISS_Allocate4 { get; set; }
        public Nullable<decimal> U_ISS_Allocate5 { get; set; }
        public Nullable<decimal> U_ISS_Allocate6 { get; set; }
        public Nullable<decimal> U_ISS_Allocate7 { get; set; }
        public Nullable<decimal> U_ISS_Allocate8 { get; set; }
        public Nullable<decimal> U_ISS_Allocate9 { get; set; }
        public Nullable<decimal> U_ISS_Allocate10 { get; set; }
    }
}
