//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AISS_WHTLINE
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public int LogInst { get; set; }
        public string U_IncomeType { get; set; }
        public string U_OtherDesc { get; set; }
        public Nullable<decimal> U_DocAmount { get; set; }
        public Nullable<decimal> U_BaseAmount { get; set; }
        public Nullable<decimal> U_TaxableAmount { get; set; }
        public string U_WHTCode { get; set; }
        public string U_WHTName { get; set; }
        public Nullable<decimal> U_WHTRate { get; set; }
        public Nullable<decimal> U_WHTAmount { get; set; }
        public string U_AcctCode { get; set; }
    }
}
