//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AISS_WHTSUBMIT
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public int LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_WHTType { get; set; }
        public string U_Branch { get; set; }
        public string U_Year { get; set; }
        public string U_Month { get; set; }
        public Nullable<System.DateTime> U_SubmitDate { get; set; }
        public string U_SubmitType { get; set; }
        public string U_AdditionNum { get; set; }
        public string U_Section { get; set; }
        public string U_MediaType { get; set; }
        public Nullable<short> U_QtySlip { get; set; }
        public Nullable<short> U_QtySheet { get; set; }
        public Nullable<decimal> U_TotalTaxableAmt { get; set; }
        public Nullable<decimal> U_TotalWHTAmt { get; set; }
        public Nullable<decimal> U_AdditionAmt { get; set; }
        public Nullable<decimal> U_TotalAmount { get; set; }
        public string U_Payer { get; set; }
        public string U_Position { get; set; }
        public string U_SortBy { get; set; }
        public string U_AllBranch { get; set; }
    }
}
