//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ISS_PP30SALES
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<System.DateTime> U_InvoiceDate { get; set; }
        public string U_InvoiceNum { get; set; }
        public Nullable<decimal> U_DocAmt0 { get; set; }
        public Nullable<decimal> U_VatAmt0 { get; set; }
        public Nullable<decimal> U_TotalAmt0 { get; set; }
        public Nullable<decimal> U_DocAmtN { get; set; }
        public Nullable<decimal> U_VatAmtN { get; set; }
        public Nullable<decimal> U_TotalAmtN { get; set; }
        public Nullable<decimal> U_SumTotalAmt { get; set; }
        public string U_TaxGroup { get; set; }
        public Nullable<System.DateTime> U_PostingDate { get; set; }
        public Nullable<decimal> U_VatRate { get; set; }
        public string U_BpCode { get; set; }
        public string U_Canceled { get; set; }
        public string U_BpName { get; set; }
        public string U_BpTaxID { get; set; }
        public string U_BpBrnCode { get; set; }
        public Nullable<decimal> U_BaseAmt { get; set; }
        public Nullable<decimal> U_DocAmt { get; set; }
        public Nullable<decimal> U_VatAmt { get; set; }
        public Nullable<decimal> U_TotalAmt { get; set; }
        public string U_VatBranch { get; set; }
        public Nullable<int> U_TAXEntry { get; set; }
        public Nullable<int> U_TAXLineId { get; set; }
    }
}
