//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ISS_TAXLINE
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<System.DateTime> U_InvoiceDate { get; set; }
        public string U_InvoiceNum { get; set; }
        public string U_BpCode { get; set; }
        public string U_BpName { get; set; }
        public string U_BpTaxID { get; set; }
        public string U_BpBrnCode { get; set; }
        public string U_BpBrnName { get; set; }
        public Nullable<decimal> U_BaseAmt { get; set; }
        public Nullable<decimal> U_BeforeVat { get; set; }
        public Nullable<decimal> U_VatAmount { get; set; }
        public Nullable<decimal> U_TotalAmt { get; set; }
        public string U_Category { get; set; }
        public string U_TaxGroup { get; set; }
        public string U_CancelVat { get; set; }
        public string U_Submitted { get; set; }
        public Nullable<System.DateTime> U_SubmitDate { get; set; }
        public Nullable<System.DateTime> U_PostingDate { get; set; }
        public string U_Addition { get; set; }
        public Nullable<decimal> U_VatRate { get; set; }
        public Nullable<decimal> U_NonDeductRate { get; set; }
        public Nullable<decimal> U_DeductAmt { get; set; }
        public Nullable<decimal> U_DeductVatAmt { get; set; }
        public Nullable<decimal> U_NonDeductAmt { get; set; }
        public Nullable<decimal> U_NonDeductVatAmt { get; set; }
        public string U_VatType { get; set; }
        public Nullable<decimal> U_DueBeforeVat { get; set; }
        public Nullable<decimal> U_DueVatAmount { get; set; }
        public Nullable<decimal> U_DueTotalAmt { get; set; }
        public Nullable<int> U_SubmitId { get; set; }
        public string U_VatBranch { get; set; }
        public Nullable<int> U_RevTransId { get; set; }
    }
}
