//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ISS_PP30
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_VatBranch { get; set; }
        public string U_Month { get; set; }
        public string U_Year { get; set; }
        public string U_TaxPeriod { get; set; }
        public string U_DateType { get; set; }
        public string U_Addition { get; set; }
        public Nullable<int> U_AddNo { get; set; }
        public Nullable<System.DateTime> U_SubmitDate { get; set; }
        public Nullable<int> U_TransId { get; set; }
        public string U_Printed { get; set; }
        public Nullable<System.DateTime> U_PrintDate { get; set; }
        public Nullable<decimal> U_SalesAmt1 { get; set; }
        public Nullable<decimal> U_SalesAmt2 { get; set; }
        public Nullable<decimal> U_SalesAmt3 { get; set; }
        public Nullable<decimal> U_TotalSalesAmt { get; set; }
        public Nullable<decimal> U_OutputTaxAmt { get; set; }
        public Nullable<decimal> U_PurAmt { get; set; }
        public Nullable<decimal> U_InputTaxAmt { get; set; }
        public Nullable<decimal> U_PayTaxAmt { get; set; }
        public Nullable<decimal> U_OverTaxAmt { get; set; }
        public Nullable<decimal> U_PCFAmt { get; set; }
        public Nullable<decimal> U_MustPayAmt { get; set; }
        public Nullable<decimal> U_OverPayAmt { get; set; }
        public Nullable<decimal> U_AdditionAmt { get; set; }
        public Nullable<decimal> U_FineAmt { get; set; }
        public Nullable<decimal> U_TotalPayAmt { get; set; }
        public Nullable<decimal> U_TotalOverAmt { get; set; }
        public string U_GLAccOutputTax { get; set; }
        public string U_GLAccInputTax { get; set; }
        public string U_GLAccPCF { get; set; }
        public string U_GLAccMustPay { get; set; }
        public string U_GLAccOverPay { get; set; }
        public string U_GLAccAdditionAmt { get; set; }
        public string U_GLAccFineAmt { get; set; }
        public string U_GLAccTotalPayAmt { get; set; }
        public string U_GLAccTotalOverAmt { get; set; }
        public string U_SubmitType { get; set; }
        public Nullable<System.DateTime> U_PostingDate { get; set; }
        public string U_SortBy { get; set; }
    }
}
