//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ISS_TAX
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_ObjectType { get; set; }
        public string U_Origin { get; set; }
        public Nullable<int> U_BaseEntry { get; set; }
        public Nullable<int> U_BaseSeries { get; set; }
        public string U_BpCode { get; set; }
        public string U_BpName { get; set; }
        public string U_VatBranch { get; set; }
        public string U_TaxType { get; set; }
        public Nullable<decimal> U_DocAmount { get; set; }
        public Nullable<int> U_TransId { get; set; }
        public Nullable<decimal> U_VatSum { get; set; }
    }
}
