//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JWS_ADDRESSCODE
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_JWS_Province { get; set; }
        public string U_JWS_County { get; set; }
        public string U_JWS_District { get; set; }
        public string U_JWS_ZipCode { get; set; }
    }
}
