//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JWS_BRANCHDETAIL
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_Name { get; set; }
        public string U_Address { get; set; }
        public string U_GLN { get; set; }
        public string U_FName { get; set; }
        public string U_FAddress { get; set; }
    }
}
