//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JWS_OAWS
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_JWS_WtmCode { get; set; }
        public Nullable<int> U_JWS_EmpId { get; set; }
        public string U_JWS_ExtEmpId { get; set; }
        public Nullable<int> U_JWS_TotalStage { get; set; }
        public Nullable<int> U_JWS_CurrentStage { get; set; }
        public string U_JWS_ObjType { get; set; }
        public Nullable<int> U_JWS_DocEntry { get; set; }
        public string U_JWS_Status { get; set; }
        public Nullable<System.DateTime> U_JWS_CreateDate { get; set; }
        public Nullable<short> U_JWS_CreateTime { get; set; }
        public Nullable<int> U_JWS_CreateBy { get; set; }
        public Nullable<System.DateTime> U_JWS_UpdateDate { get; set; }
        public Nullable<short> U_JWS_UpdateTime { get; set; }
        public Nullable<int> U_JWS_UpdateBy { get; set; }
        public string U_JWS_Email { get; set; }
        public string U_JWS_WtmName { get; set; }
    }
}
