//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_WORKORDER
    {
        public int ID { get; set; }
        public string Commander_Name { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Commander_Datetime { get; set; }
        public string Contact_Name { get; set; }
        public string Telephone { get; set; }
        public string Recipient_Name { get; set; }
        public Nullable<System.DateTime> Commander_Recipient { get; set; }
    }
}
