//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_BILL_BANK
    {
        public int ID { get; set; }
        public string WorkOrder_ID { get; set; }
        public string Bank_Name { get; set; }
        public string Option { get; set; }
        public string Other { get; set; }
    }
}
