//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_BILL_WORKORDER
    {
        public int ID { get; set; }
        public string WorkOrder_ID { get; set; }
        public string Commander_Code { get; set; }
        public string Commander_Name { get; set; }
        public string Commander_Department { get; set; }
        public Nullable<System.DateTime> Commander_Datetime { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Tel { get; set; }
        public string Recipient_Code { get; set; }
        public string Recipient_Name { get; set; }
        public Nullable<System.DateTime> Recipient_Datetime { get; set; }
        public string Type_Work { get; set; }
        public string Remark { get; set; }
        public string RemarkAdmin { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Last_Datetime { get; set; }
        public string wk_path_img { get; set; }
        public Nullable<int> round { get; set; }
        public string mtyear { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string tracking_first { get; set; }
        public string tracking_last { get; set; }
        public string Commander_JobTitle { get; set; }
        public Nullable<int> Work_ID { get; set; }
        public Nullable<int> Postel_ID { get; set; }
        public string MS_1 { get; set; }
        public string MS_2 { get; set; }
        public string MS_3 { get; set; }
        public string MS_4 { get; set; }
    }
}
