//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_POSTOFFICE_REF
    {
        public int ID { get; set; }
        public string post_wk_id { get; set; }
        public string post_type { get; set; }
        public string post_name { get; set; }
        public string post_zip { get; set; }
        public string post_ems { get; set; }
        public string post_emsrev { get; set; }
        public Nullable<decimal> post_price { get; set; }
        public Nullable<int> post_round { get; set; }
        public string post_mtyear { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public Nullable<decimal> post_sumprice { get; set; }
        public string post_success_id { get; set; }
    }
}
