//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_BILL_POSTOFFICE
    {
        public int ID { get; set; }
        public string WorkOrder_ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Postel { get; set; }
        public string Itemcode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string EMSRev { get; set; }
        public string Ck_print { get; set; }
        public string AC_code { get; set; }
        public string ps_code { get; set; }
    }
}
