//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_CREDITNOTE
    {
        public int ID { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<int> CreditNo { get; set; }
        public Nullable<System.DateTime> DateNote { get; set; }
        public Nullable<System.DateTime> DueDateNote { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Refno { get; set; }
    }
}
