//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MCT_BILLING
    {
        public int ID { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<int> InvNo { get; set; }
        public Nullable<System.DateTime> DateBill { get; set; }
        public Nullable<System.DateTime> DueDateBill { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public string TypeID { get; set; }
        public Nullable<System.DateTime> CheckDueDate { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> DateRev { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> Receivedate { get; set; }
        public string Refno { get; set; }
    }
}
