//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_VACCINATE
    {
        public int ID { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<bool> VaccinateStatus { get; set; }
        public string Remark { get; set; }
    }
}
