//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_RELATION
    {
        public string CardCode { get; set; }
        public string Founded { get; set; }
        public string Product { get; set; }
        public string Brand { get; set; }
        public string Turnover { get; set; }
        public string Target { get; set; }
        public string Store { get; set; }
        public string Schannel { get; set; }
        public string Keyoutlet { get; set; }
        public string Operate { get; set; }
        public string Mshare { get; set; }
        public string Machinery { get; set; }
        public string Quality { get; set; }
        public string KeyProduct { get; set; }
        public string Mcard { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string BusinessOther { get; set; }
        public string Frequency { get; set; }
        public string Bidding { get; set; }
        public string Stock { get; set; }
        public string Plant { get; set; }
        public string Question { get; set; }
        public string Approve { get; set; }
        public string Distribute { get; set; }
        public string Competitor { get; set; }
        public string MinShelf { get; set; }
        public string Listing { get; set; }
        public string Pattern { get; set; }
        public string Review { get; set; }
        public string Agreement { get; set; }
        public string Return { get; set; }
        public string Bmargin { get; set; }
        public string Margin { get; set; }
        public string PurchaseOther { get; set; }
        public string NameKey1 { get; set; }
        public string NameDetailP1 { get; set; }
        public string NameKey2 { get; set; }
        public string NameDetailP2 { get; set; }
        public string NameKey3 { get; set; }
        public string NameDetailP3 { get; set; }
        public string NameKey4 { get; set; }
        public string NameDetailP4 { get; set; }
        public string NameKey5 { get; set; }
        public string NameDetailP5 { get; set; }
        public string NameKey6 { get; set; }
        public string NameDetailP6 { get; set; }
        public string NameKey7 { get; set; }
        public string NameDetailP7 { get; set; }
        public string NameKey8 { get; set; }
        public string NameDetailP8 { get; set; }
        public string NameKey9 { get; set; }
        public string NameDetailP9 { get; set; }
        public string NameKey10 { get; set; }
        public string NameDetailP10 { get; set; }
        public string NameKey11 { get; set; }
        public string NameDetailP11 { get; set; }
        public string NameKey12 { get; set; }
        public string NameDetailP12 { get; set; }
        public string NameKey13 { get; set; }
        public string NameDetailP13 { get; set; }
        public string NameKey14 { get; set; }
        public string NameDetailP14 { get; set; }
        public string NameKey15 { get; set; }
        public string NameDetailP15 { get; set; }
        public string NameKey16 { get; set; }
        public string NameDetailP16 { get; set; }
        public string NameKey17 { get; set; }
        public string NameDetailP17 { get; set; }
        public string NameKey18 { get; set; }
        public string NameDetailP18 { get; set; }
        public string NameKey19 { get; set; }
        public string NameDetailP19 { get; set; }
        public string NameKey20 { get; set; }
        public string NameDetailP20 { get; set; }
        public string NameKey21 { get; set; }
        public string NameDetailP21 { get; set; }
        public string NameKey22 { get; set; }
        public string NameDetailP22 { get; set; }
        public string NameKey23 { get; set; }
        public string NameDetailP23 { get; set; }
        public string NameKey24 { get; set; }
        public string NameDetailP24 { get; set; }
        public string NameKey25 { get; set; }
        public string NameDetailP25 { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
