//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_CHECKIN
    {
        public int ID { get; set; }
        public string Topic { get; set; }
        public string TopicOthers { get; set; }
        public string Subject { get; set; }
        public string SelectOptions { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string CustomerCode { get; set; }
        public string Branch { get; set; }
        public string SaleCode { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string Position { get; set; }
        public string Telephone { get; set; }
        public string Information { get; set; }
        public string NextAction { get; set; }
        public string Compititor { get; set; }
        public string ProjectRequest { get; set; }
        public string AttachedFile { get; set; }
        public string AttachedFile2 { get; set; }
        public string AttachedFile3 { get; set; }
        public string AttachedFile4 { get; set; }
        public string AttachedFile5 { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string UserSubmit { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    }
}
