//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_LICENSE_LOG
    {
        public int ID { get; set; }
        public string DocumentNo { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string StorageLocation { get; set; }
        public string LicenseFile_Path { get; set; }
        public string TotalR { get; set; }
        public string Tel { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> PIC { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
