//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_CHECKIN_READ
    {
        public int ID { get; set; }
        public Nullable<int> Checkin_ID { get; set; }
        public string Usercode { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
