//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_TRADEMARK_LOG
    {
        public int ID { get; set; }
        public string RequestID { get; set; }
        public string RegisterNo { get; set; }
        public string TrademarkDt_TH { get; set; }
        public string TrademarkDt_ENG { get; set; }
        public string TrademarkPic { get; set; }
        public string TrademarkFile { get; set; }
        public string GroupP { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
