//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_PLANTPL
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_NameEng { get; set; }
        public string U_Account { get; set; }
        public string U_Level { get; set; }
        public string U_Bold { get; set; }
        public string U_CostCenter { get; set; }
        public string U_NameTh { get; set; }
        public string U_MapCode { get; set; }
        public Nullable<int> U_line { get; set; }
        public Nullable<int> U_group { get; set; }
        public Nullable<int> U_ReportGrp { get; set; }
        public string U_AcctByGrp { get; set; }
    }
}
