//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISS_RptCriteria
    {
        public int DocEntry { get; set; }
        public string RptName { get; set; }
        public string Branch { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string DateType { get; set; }
        public string SortByField { get; set; }
        public string InvNums { get; set; }
        public string Canceled { get; set; }
        public string TaxGroup { get; set; }
    }
}
