//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISS_Menu
    {
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuHead { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public Nullable<int> HasSubMenu { get; set; }
        public string MenuType { get; set; }
        public string ParentMenuID { get; set; }
    }
}
