//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSTS
    {
        public int Code { get; set; }
        public Nullable<int> Technician { get; set; }
        public string Choice { get; set; }
        public Nullable<int> GroupCode { get; set; }
    }
}
