//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBS_WGE_Entities : DbContext
    {
        public DBS_WGE_Entities()
            : base("name=DBS_WGE_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocationTest> LocationTest { get; set; }
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<OHEM> OHEM { get; set; }
        public virtual DbSet<OINV> OINV { get; set; }
        public virtual DbSet<ORIN> ORIN { get; set; }
        public virtual DbSet<OSLP> OSLP { get; set; }
        public virtual DbSet<C_MCT_CREDITNOTE> C_MCT_CREDITNOTE { get; set; }
        public virtual DbSet<C_MCT_DOCUMENT> C_MCT_DOCUMENT { get; set; }
        public virtual DbSet<C_MCT_OTHER> C_MCT_OTHER { get; set; }
        public virtual DbSet<C_MCT_MAP> C_MCT_MAP { get; set; }
        public virtual DbSet<C_MCT_RECEIVE> C_MCT_RECEIVE { get; set; }
        public virtual DbSet<C_MCT_BILLING> C_MCT_BILLING { get; set; }
        public virtual DbSet<OCTG> OCTG { get; set; }
        public virtual DbSet<OUDP> OUDP { get; set; }
        public virtual DbSet<C_MCT_BILL_BANK> C_MCT_BILL_BANK { get; set; }
        public virtual DbSet<C_MCT_BILL_GENERAL> C_MCT_BILL_GENERAL { get; set; }
        public virtual DbSet<C_MCT_BILL_POSTOFFICE> C_MCT_BILL_POSTOFFICE { get; set; }
        public virtual DbSet<C_MCT_BILL_WORKORDER> C_MCT_BILL_WORKORDER { get; set; }
        public virtual DbSet<C_MCT_POSTOFFICE_REF> C_MCT_POSTOFFICE_REF { get; set; }
    
        public virtual ObjectResult<ReportPostel_Monthly_Result> ReportPostel_Monthly(Nullable<int> choice, string mtyear1, string mtyear2, Nullable<System.DateTime> datefrom, Nullable<System.DateTime> dateto)
        {
            var choiceParameter = choice.HasValue ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(int));
    
            var mtyear1Parameter = mtyear1 != null ?
                new ObjectParameter("mtyear1", mtyear1) :
                new ObjectParameter("mtyear1", typeof(string));
    
            var mtyear2Parameter = mtyear2 != null ?
                new ObjectParameter("mtyear2", mtyear2) :
                new ObjectParameter("mtyear2", typeof(string));
    
            var datefromParameter = datefrom.HasValue ?
                new ObjectParameter("datefrom", datefrom) :
                new ObjectParameter("datefrom", typeof(System.DateTime));
    
            var datetoParameter = dateto.HasValue ?
                new ObjectParameter("dateto", dateto) :
                new ObjectParameter("dateto", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportPostel_Monthly_Result>("ReportPostel_Monthly", choiceParameter, mtyear1Parameter, mtyear2Parameter, datefromParameter, datetoParameter);
        }
    }
}
