//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCodingTest.Models.L2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public int USR_KEY { get; set; }
        public int USR_EMP { get; set; }
        public string USR_NO { get; set; }
        public string USR_INTL { get; set; }
        public string USR_NAME { get; set; }
        public string USR_SURNME { get; set; }
        public string USR_E_NAME { get; set; }
        public string USR_LOGIN { get; set; }
        public string USR_PASSWORD { get; set; }
        public string USR_LMAIL { get; set; }
        public string USR_JCODE { get; set; }
        public string USR_JTHAIDESC { get; set; }
        public string USR_DCODE { get; set; }
        public string USR_DTHAIDESC { get; set; }
        public string USR_BTHAIDESC { get; set; }
    }
}
